# strength of shift boosts while flying
boostMultiplier: 2.5

# strength of launch off of the ground
launchModifier: 3.0

wings:
  displayName: "<!italic><aqua>Wings</aqua>"
  lore:
    - "<!italic><blue>Shift Boost</blue>"
    - "<!italic><blue>Cushioning</blue>"
  unbreakable: true # whether wings should have unbreakable property
