# shift boosts while flying
boost:
  velocityMultiplier: 2.5
  particle:
    enabled: true
    count: 15
    particleType: FLAME
    speed: 1.0
  cooldown: 0
# launch by holding shift, looking up, and jumping
launch:
  velocityMultiplier: 3.0
  particle:
    enabled: true
    count: 5
    particleType: EXPLOSION
    speed: 1.0
  sound:
    enabled: true
    volume: 0.5
# wings item
wings:
  # make sure to include <!italic> tag if you want to remove minecraft's italics
  displayName: "<!italic><aqua>Wings</aqua>"
  lore:
    - "<!italic><blue>Shift Boost</blue>"
    - "<!italic><blue>Cushioning</blue>"
  unbreakable: true # whether wings should have unbreakable property
  enchantGlint: true
