name: GardensWings
version: 1.0.0
author: Bright_Steel
main: com.gardensmc.wings.spigot.WingsSpigot
api-version: 1.20
commands:
  wings:
    permission: wings.get, wings.give, wings.reload
    description: Get or give wings.
    usage: /<command> [get|give|reload]
